version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: topicdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sa
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"

  topic-manager-service:
    restart: on-failure
    build: ./
    expose:
      - "10222"
    ports:
      - 10222:10222
    depends_on:
      - docker-mysql
